# Generated by Django 5.0.2 on 2024-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.CharField(max_length=255)),
                ("num_seat", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "buses",
            },
        ),
    ]
