# Generated by Django 5.0.2 on 2024-04-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_facility_bus_facility_order_trip_ticket_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name_plural": "facilities"},
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="db.order",
            ),
        ),
    ]
