# Generated by Django 5.0.2 on 2024-05-16 10:05

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_alter_ticket_options_alter_ticket_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(null=True, upload_to=db.models.bus_image_path),
        ),
    ]
